---
# this playbook ...

- hosts: software-factory
  connection: local
  sudo: True
  user: root
  roles:
     - common
  vars_files:
    - group_vars/software-factory


- hosts: software-factory
  connection: local
  sudo: True
  user: tomcat
  roles:
     - maven
     - git
     - jee-server
     - smoke_test
  vars_files:
    - group_vars/software-factory


