---
# this playbook ...

- hosts: software-factory
  connection: local
  sudo: True
  user: root
  roles:
     - common


- hosts: software-factory
  connection: local
  sudo: True
  user: tomcat
  roles:
     - maven
     - git
     - jee-server
     - smoke_test


