---
# install nexus in tomcat

- name: Lookup nexus variables
  include_vars: nexus.yml

- name: Download Nexus
  local_action: get_url url={{ nexus.download_url }}   
           dest=/tmp/nexus.war  force=no

- name: Install Nexus war
  copy: src=/tmp/nexus.war
    dest={{tomcat_home}}/webapps/nexus.war 
    force=no  owner=tomcat group=tomcat 
  notify: restart tomcat
   
