---
# install Gitblit in tomcat

- name: Lookup gitblit variables
  include_vars: gitblit.yml

- name: Lookup tomcat variables
  include_vars: tomcat.yml

- name: Download Gitblit
  local_action: get_url url={{ gitblit.download_url }}
           dest=/tmp/gitblit.war  force=no

- name: Install Gitblit war
  copy: src=/tmp/gitblit.war 
    dest={{tomcat.home}}/webapps/gitblit.war 
    force=yes owner=tomcat group=tomcat 
  notify: restart tomcat

